development:
  secret_key_base: <%= ENV["DEVELOPMENT_SECRET_TOKEN"] %>
test:
  secret_key_base: <%= ENV["TEST_SECRET_TOKEN"] %>
staging:
  secret_key_base: <%= ENV["STAGING_SECRET_TOKEN"] %>
production:
  secret_key_base: <%= LineOfBusiness.scoped_env('PRODUCTION_SECRET_TOKEN') %>    